# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-101865856-1
favicon: https://secure.gravatar.com/avatar/9f927ffa7e383a4cdbf2ae32191fe70f?r=g&d=https://avatar-cdn.atlassian.com/default/32&s=32
twitter: ramons03
google_plus:
fb_admins:
fb_app_id:
